version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "order-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jteck0z8f4en"
s3_prefix = "order-app"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
